import { ArrowLeft, CalendarDays, Download, FileText, Landmark, MessageSquareText, WalletCards } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DocumentUpload } from "@/components/crm/document-upload";
import { caseStages, formatCurrency, formatDate, requireStaff } from "@/lib/crm";
import { addCaseNote, addTask, savePayment, toggleTask, updateCaseStage } from "../../actions";

export default async function CaseDetailPage({params}:{params:Promise<{id:string}>}){
  const{id}=await params;const{supabase}=await requireStaff();
  const[{data:item},{data:notes},{data:tasks},{data:documents},{data:payments},{data:activities}]=await Promise.all([
    supabase.from("cases").select("*,clients(*),profiles(full_name)").eq("id",id).single(),
    supabase.from("case_notes").select("*,profiles(full_name)").eq("case_id",id).order("created_at",{ascending:false}),
    supabase.from("tasks").select("*").eq("case_id",id).order("completed_at",{ascending:true}).order("due_at"),
    supabase.from("documents").select("*").eq("case_id",id).is("deleted_at",null).order("created_at",{ascending:false}),
    supabase.from("payments").select("*").eq("case_id",id).order("created_at",{ascending:false}),
    supabase.from("activities").select("*").eq("entity_type","case").eq("entity_id",id).order("created_at",{ascending:false}).limit(12)
  ]); if(!item)notFound(); const client=item.clients as unknown as {full_name:string;email:string;phone:string};
  return <main className="crm-content case-detail"><Link className="back-link" href="/app/casos"><ArrowLeft size={16}/> Voltar aos casos</Link><header className="case-header"><div><span className={`stage-badge stage-${item.stage}`}>{item.stage.replaceAll("_"," ")}</span><h1>{item.title}</h1><p>{client.full_name} • {item.institution||"Instituição não informada"}</p></div><form action={updateCaseStage} className="stage-form"><input type="hidden" name="id" value={id}/><label>Etapa<select name="stage" defaultValue={item.stage}>{caseStages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><button className="app-button primary">Atualizar</button></form></header>
    <section className="case-summary"><div><Landmark/><span>Instituição<strong>{item.institution||"—"}</strong></span></div><div><FileText/><span>Produto<strong>{item.product_name||item.case_type.replaceAll("_"," ")}</strong></span></div><div><WalletCards/><span>Valor analisado<strong>{formatCurrency(item.analyzed_amount)}</strong></span></div><div><CalendarDays/><span>Aberto em<strong>{formatDate(item.created_at)}</strong></span></div></section>
    <div className="case-workspace"><div className="case-primary"><section className="app-panel"><div className="panel-heading"><div><p className="app-kicker">Documentos</p><h2>Dossiê do caso</h2></div><span>{documents?.length||0} arquivos</span></div><div className="document-list">{(documents||[]).map(doc=><a key={doc.id} href={`/api/documents/${doc.id}`} target="_blank"><span className="doc-icon"><FileText/></span><div><strong>{doc.original_name}</strong><small>{doc.category.replaceAll("_"," ")} • {(doc.size_bytes/1024/1024).toFixed(1)} MB</small></div><Download size={17}/></a>)}{!documents?.length&&<div className="empty-inline">Nenhum documento enviado.</div>}</div><DocumentUpload caseId={id}/></section>
      <section className="app-panel"><div className="panel-heading"><div><p className="app-kicker">Atendimento</p><h2>Linha do tempo</h2></div></div><form action={addCaseNote} className="note-form"><input type="hidden" name="case_id" value={id}/><select name="note_type"><option value="observacao">Observação</option><option value="whatsapp">WhatsApp</option><option value="ligacao">Ligação</option><option value="reuniao">Reunião</option><option value="decisao">Decisão</option></select><textarea name="body" required placeholder="Registre o contato, a decisão e o próximo passo."/><button className="app-button primary"><MessageSquareText size={16}/> Registrar nota</button></form><div className="timeline">{(notes||[]).map(note=><article key={note.id}><span/><div><header><strong>{note.note_type}</strong><small>{formatDate(note.created_at)} • {(note.profiles as unknown as {full_name:string})?.full_name}</small></header><p>{note.body}</p></div></article>)}{!notes?.length&&<div className="empty-inline">Nenhuma interação registrada.</div>}</div></section></div>
      <aside className="case-aside"><section className="app-panel"><p className="app-kicker">Próximos passos</p><h2>Tarefas</h2><div className="mini-task-list">{(tasks||[]).map(task=><div className={task.completed_at?"completed":""} key={task.id}><form action={toggleTask}><input type="hidden" name="id" value={task.id}/><input type="hidden" name="complete" value={task.completed_at?"false":"true"}/><button>{task.completed_at?"↺":"✓"}</button></form><span><strong>{task.title}</strong><small>{formatDate(task.due_at)}</small></span></div>)}</div><form action={addTask} className="stack-form compact"><input type="hidden" name="case_id" value={id}/><input name="title" required placeholder="Nova tarefa"/><input name="due_at" type="datetime-local"/><select name="priority" defaultValue="2"><option value="1">Alta</option><option value="2">Normal</option><option value="3">Baixa</option></select><button className="app-button">Adicionar</button></form></section>
      <section className="app-panel"><p className="app-kicker">Financeiro</p><h2>Pagamentos</h2><div className="payment-list">{(payments||[]).map(payment=><div key={payment.id}><strong>{formatCurrency(payment.amount)}</strong><span className={`stage-badge payment-${payment.status}`}>{payment.status}</span><small>Venc. {formatDate(payment.due_date)}</small></div>)}</div><form action={savePayment} className="stack-form compact"><input type="hidden" name="case_id" value={id}/><input name="amount" required inputMode="decimal" placeholder="Valor"/><input name="due_date" type="date"/><select name="method"><option value="pix">Pix</option><option value="boleto">Boleto</option><option value="transferencia">Transferência</option><option value="outro">Outro</option></select><select name="status" defaultValue="pendente"><option value="pendente">Pendente</option><option value="parcial">Parcial</option><option value="pago">Pago</option><option value="reembolsado">Reembolsado</option><option value="cancelado">Cancelado</option></select><button className="app-button">Registrar</button></form></section>
      <section className="app-panel audit-panel"><p className="app-kicker">Auditoria</p><h2>Atividade</h2>{(activities||[]).map(activity=><div key={activity.id}><strong>{activity.action.replaceAll("_"," ")}</strong><small>{formatDate(activity.created_at)}</small></div>)}</section></aside></div>
  </main>;
}

