import { ArrowUpRight, Check, MessageCircle, UserRoundCheck } from "lucide-react";
import { assignLead, convertLead, updateLeadStage } from "../actions";
import { caseTypes, formatDate, leadStages, requireStaff } from "@/lib/crm";

export default async function LeadsPage({searchParams}:{searchParams:Promise<{q?:string;stage?:string}>}) {
  const params=await searchParams; const {supabase,profile}=await requireStaff();
  let query=supabase.from("leads").select("*,profiles(full_name)").order("created_at",{ascending:false});
  if(params.stage) query=query.eq("stage",params.stage); if(params.q) query=query.or(`name.ilike.%${params.q}%,email.ilike.%${params.q}%,institution.ilike.%${params.q}%`);
  const {data:leads}=await query;
  return <main className="crm-content"><header className="page-heading"><div><p className="app-kicker">Comercial</p><h1>Leads</h1><p>Da primeira triagem até a abertura do caso.</p></div></header>
    <form className="filter-bar"><input name="q" defaultValue={params.q} placeholder="Buscar nome, e-mail ou instituição"/><select name="stage" defaultValue={params.stage||""}><option value="">Todos os estágios</option>{leadStages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button className="app-button" type="submit">Filtrar</button></form>
    <div className="lead-grid">{(leads||[]).map((lead)=><article className="lead-card" key={lead.id}><div className="lead-card-top"><span className={`stage-badge stage-${lead.stage}`}>{lead.stage.replaceAll("_"," ")}</span><small>{formatDate(lead.created_at)}</small></div><h2>{lead.name}</h2><p>{lead.institution} • {lead.issue_type}</p><dl><div><dt>Carteira</dt><dd>{lead.amount_range}</dd></div><div><dt>Urgência</dt><dd>{lead.urgency}</dd></div></dl>{lead.duplicate_of&&<div className="duplicate-note">Possível contato duplicado</div>}<div className="lead-actions"><a className="icon-text" href={`https://wa.me/${lead.normalized_phone}`} target="_blank"><MessageCircle size={16}/> WhatsApp</a>{!lead.owner_id&&<form action={assignLead}><input type="hidden" name="id" value={lead.id}/><button className="icon-text"><UserRoundCheck size={16}/> Assumir</button></form>}</div><details><summary>Atualizar estágio</summary><form action={updateLeadStage} className="inline-form"><input type="hidden" name="id" value={lead.id}/><select name="stage" defaultValue={lead.stage}>{leadStages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input name="lost_reason" placeholder="Motivo se perdido"/><button title="Salvar"><Check size={17}/></button></form></details>{lead.stage!=="convertido"&&<details><summary>Converter em caso</summary><form action={convertLead} className="stack-form"><input type="hidden" name="lead_id" value={lead.id}/><input name="title" defaultValue={`${lead.issue_type} • ${lead.institution}`} required/><select name="case_type" defaultValue="analise_inicial">{caseTypes.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button className="app-button primary">Criar cliente e caso <ArrowUpRight size={16}/></button></form></details>}<footer>{lead.owner_id?<span>Responsável: {(lead.profiles as unknown as {full_name:string}|null)?.full_name||profile.full_name}</span>:<span>Sem responsável</span>}</footer></article>)}{!leads?.length&&<div className="empty-state"><ContactIcon/><h2>Nenhum lead encontrado</h2><p>Novas triagens enviadas pelo site aparecerão aqui.</p></div>}</div>
  </main>;
}
function ContactIcon(){return <span className="empty-icon"><UserRoundCheck/></span>}

